### ISSUE TITLE
How should I use the displacement data and velocity field data from the program

### ISSUE THREAD

**Issue by Feyily** [david-kamensky/CouDALFISh#1]
Hello, Professor Kamensky.

I am a beginner in fluid mechanics simulation. Recently, I am doing a project related to heart valve simulation. When I was looking for the literature, I had the honor to see your published paper *An immersogeometric variational framework for fluid-structure interaction Application to bioprosthetic heart valves*, and I was very interested in the results.

I downloaded the code from this repository and ran `heartValve.py`, and I got a set of files about displacement as shown in the following figure.
![image-20210115165933083](https://raw.githubusercontent.com/Feyily/imgbed/master/U390cc01242794a7fa14e00dab6c882bbD.jpg)

and a set of solved `.pvd` files containing speed `u` and pressure `p`.
![image-20210115170156296](https://raw.githubusercontent.com/Feyily/imgbed/master/Ua61106fadd014bbbbb0f0797c6828dfbw.jpg)

I am very confused, how should I deal with the displacement data and the velocity field data obtained from the solution, and finally render into the animation effect shown in your paper?
![image-20210105115013809](https://raw.githubusercontent.com/Feyily/imgbed/master/U335d66606083460da0ebf612b2a21b5bv.jpg)

Or how should I use the displacement data and velocity field data from the program?

Thank you very much for your reply.

**Comment by david-kamensky** [comment]
**For the displacement data:**  The mesh that DOLFIN sees in tIGAr-based isogeometric analysis is actually a mesh in the spline parameter space, not in physical space.  To visualize the deformed configuration of the shell structure, you need to apply some filters in Paraview.  This process is explained in more detail in the comments at the bottom of the following demo distributed with ShNAPr:

https://github.com/david-kamensky/ShNAPr/blob/master/demos/reefKnot.py

Note that, in addition to the three displacement components, you must also load the files `F-x.pvd`, `F-y.pvd`, `F-z.pvd`, and `F-w.pvd`, which define the geometry of the reference configuration.  

**For the velocity data:**  The figures from the 2015 paper are based on output from an older Fortran research code implementing a similar approach, and were rendered using Tecplot.  The "volume rendering" (which is not (or was not at the time) directly supported by Tecplot) is actually a collection of many nearly-transparent slices perpendicular to the z-axis.  You can produce a similar effect in Paraview using a slice filter.  (Paraview does include volume rendering functionality, although it looks quite different.)

**Comment by Feyily** [comment]
Thank you very much for your answer. I will try these steps in Paraview as you suggested. Thank you again for your reply.❤
